version: '3.8'
services:
  db:
    container_name: flex_db
    image: postgres
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  flex_app:
    container_name: flex_app
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  sql: